version: '3'

services:
    # Serve static webpages and proxy to APIs
    # CRA dev server in dev and nginx in production
    webserver:
        build:
            target: development # Determine dev or prod
        image: local/webapp:client
        restart: unless-stopped
        volumes:
            - ./client:/home/node/app
        ports:
            - 3000:3000

    api:
        command: nodemon --inspect=0.0.0.0:9229 dist/workers/api.worker.js
        image: local/webapp:server
        restart: unless-stopped
        ports:
            - 9229:9229
        volumes:
            - ./server/dist:/home/node/app/dist
    
    live:
        command: nodemon --inspect=0.0.0.0:9230 dist/workers/live.worker.js
        image: local/webapp:server
        restart: unless-stopped
        ports:
            - 9230:9230
        volumes:
            - ./server/dist:/home/node/app/dist

    db: # Postgres with Timescale extension
        ports:
            - 5432:5432 # Expose ports
        restart: unless-stopped
        volumes:
          - dbdata:/data/db

    redis:
        ports:
            - 6379:6379 # Expose ports

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
